program MapleServer;

uses
  Forms,
  Generics.Collections,
  Main in 'Main.pas' {frmGUI},
  BitTools in 'Tools\BitTools.pas',
  MapleStream in 'Tools\MapleStream.pas',
  Utils in 'Tools\Utils.pas',
  DatabaseConnection in 'DatabaseConnection.pas',
  Settings in 'Settings.pas' {frmSettings},
  MapleCrypt in 'Packet\MapleCrypt.pas',
  MaplePacketCreator in 'Packet\MaplePacketCreator.pas',
  OpcodeHandler in 'Packet\OpcodeHandler.pas',
  PacketProcessor in 'Packet\PacketProcessor.pas',
  AfterLoginHandler in 'Packet\PacketHandlers\AfterLoginHandler.pas',
  CharOperationHandler in 'Packet\PacketHandlers\CharOperationHandler.pas',
  AuthenticationHandler in 'Packet\PacketHandlers\AuthenticationHandler.pas',
  PlayerLoggedinHandler in 'Packet\PacketHandlers\PlayerLoggedinHandler.pas',
  PlayerActionHandler in 'Packet\PacketHandlers\PlayerActionHandler.pas',
  MapleMapObject in 'Server\MapleMapObject.pas',
  MapleNPC in 'Server\MapleNPC.pas',
  NPCActionHandler in 'Packet\PacketHandlers\NPCActionHandler.pas',
  QuestActionHandler in 'Packet\PacketHandlers\QuestActionHandler.pas',
  ItemActionHandler in 'Packet\PacketHandlers\ItemActionHandler.pas',
  GameLogic in 'Tools\GameLogic.pas',
  CommandProcessor in 'Server\CommandProcessor.pas',
  WarpCommands in 'Server\CommandHandlers\WarpCommands.pas',
  PlayerMiscHandler in 'Packet\PacketHandlers\PlayerMiscHandler.pas',
  QuestDataProvider in 'Server\DataProvider\QuestDataProvider.pas',
  ClientStatusHandler in 'Packet\PacketHandlers\ClientStatusHandler.pas',
  MapleCharacter in 'Character\MapleCharacter.pas',
  MapleInventory in 'Character\MapleInventory.pas',
  MapleItem in 'Character\MapleItem.pas',
  MapleQuest in 'Character\MapleQuest.pas',
  MovementParser in 'Server\MovementParser.pas',
  MapleMap in 'Server\MapleMap.pas',
  MaplePortal in 'Server\MaplePortal.pas',
  ItemDataProvider in 'Server\DataProvider\ItemDataProvider.pas',
  MapDataProvider in 'Server\DataProvider\MapDataProvider.pas',
  ChannelServer in 'Communication\ChannelServer.pas',
  MapleClient in 'Communication\MapleClient.pas',
  MapleServerHandler in 'Communication\MapleServerHandler.pas',
  AttackParser in 'Server\AttackParser.pas',
  MapleMonster in 'Server\MapleMonster.pas',
  MonsterActionHandler in 'Packet\PacketHandlers\MonsterActionHandler.pas',
  DropDataProvider in 'Server\DataProvider\DropDataProvider.pas',
  DropHandler in 'Server\DropHandler.pas',
  MTRand in 'Tools\MTRand.pas',
  CreateAccount in 'CreateAccount.pas' {frmCreateAcc},
  PlayerStatHandler in 'Packet\PacketHandlers\PlayerStatHandler.pas',
  PlayerCommands in 'Server\CommandHandlers\PlayerCommands.pas',
  Skills in 'Character\Skills.pas',
  SkillDataProvider in 'Server\DataProvider\SkillDataProvider.pas',
  UseSkillHandler in 'Packet\PacketHandlers\UseSkillHandler.pas',
  BuffDataProvider in 'Server\DataProvider\BuffDataProvider.pas',
  Buffs in 'Character\Buffs.pas',
  PlayerInventory in 'Character\PlayerInventory.pas',
  PlayerBuffs in 'Character\PlayerBuffs.pas',
  Scheduler in 'Tools\Scheduler.pas',
  WorldServer in 'Communication\WorldServer.pas',
  MapleReactor in 'Server\MapleReactor.pas',
  ReactorDataProvider in 'Server\DataProvider\ReactorDataProvider.pas',
  ReactorActionHandler in 'Packet\PacketHandlers\ReactorActionHandler.pas',
  ShopDataProvider in 'Server\DataProvider\ShopDataProvider.pas',
  BuddyList in 'Character\BuddyList.pas',
  SummonActionHandler in 'Packet\PacketHandlers\SummonActionHandler.pas',
  PlayerChatHandler in 'Packet\PacketHandlers\PlayerChatHandler.pas',
  MapleParty in 'Character\MapleParty.pas',
  SpawnPoint in 'Server\SpawnPoint.pas',
  LifeDataProvider in 'Server\DataProvider\LifeDataProvider.pas',
  PlayerGroupHandler in 'Packet\PacketHandlers\PlayerGroupHandler.pas',
  MapDebug in 'MapDebug.pas' {frmMapDebug},
  MapCommands in 'Server\CommandHandlers\MapCommands.pas',
  TestCommands in 'Server\CommandHandlers\TestCommands.pas',
  NPCConversation in 'Scripting\NPCConversation.pas',
  ScriptHelper in 'Scripting\ScriptHelper.pas',
  QuestScript in 'Scripting\QuestScript.pas',
  PortalScript in 'Scripting\PortalScript.pas',
  EventScript in 'Scripting\EventScript.pas',
  MapleSummon in 'Character\MapleSummon.pas',
  Footholds in 'Server\Footholds.pas',
  ChecksumCommand in 'Server\CommandHandlers\ChecksumCommand.pas',
  PlayerInteractionHandler in 'Packet\PacketHandlers\PlayerInteractionHandler.pas',
  Trade in 'Character\Trade.pas',
  BuffStat in 'Character\BuffStat.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Delphi MapleStory Server';
  Application.CreateForm(TfrmGUI, frmGUI);
  Application.CreateForm(TfrmSettings, frmSettings);
  Application.CreateForm(TfrmCreateAcc, frmCreateAcc);
  Application.CreateForm(TfrmMapDebug, frmMapDebug);
  Application.Run;
end.
